"""initial schema

The two ledgers described in docs/design.md: an immutable ingestion audit trail
(ingestion_batches and its correction/reject rows) and a versioned projection
ledger (funds, projection_versions, cashflows and the derived nav_schedules,
nav_points and fx_forward_trades), with fund_current_version as the pointer
serving reads. Reference data is seeded separately in revision 0002.

Revision ID: 0001
Revises: 
Create Date: 2026-08-30 22:06:00.456186

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

import riskview.db.types  # custom column types render as riskview.db.types.<Name>

# revision identifiers, used by Alembic.
revision: str = '0001'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cashflow_types',
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('code', name=op.f('pk_cashflow_types'))
    )
    op.create_table('currencies',
    sa.Column('code', sa.String(length=3), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('code', name=op.f('pk_currencies'))
    )
    op.create_table('ingestion_batches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_filename', sa.String(length=255), nullable=False),
    sa.Column('content_sha256', sa.String(length=64), nullable=False),
    sa.Column('byte_size', sa.Integer(), nullable=False),
    sa.Column('received_at', riskview.db.types.UtcDateTime(), nullable=False),
    sa.Column('accepted_count', sa.Integer(), nullable=False),
    sa.Column('corrected_count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ingestion_batches')),
    sa.UniqueConstraint('content_sha256', name=op.f('uq_ingestion_batches_content_sha256'))
    )
    op.create_table('funds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('base_currency', sa.String(length=3), nullable=False),
    sa.Column('created_at', riskview.db.types.UtcDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['base_currency'], ['currencies.code'], name=op.f('fk_funds_base_currency_currencies')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_funds')),
    sa.UniqueConstraint('name', name=op.f('uq_funds_name'))
    )
    op.create_table('ingestion_corrections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('batch_id', sa.Integer(), nullable=False),
    sa.Column('line', sa.Integer(), nullable=False),
    sa.Column('row_id', sa.String(length=64), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['ingestion_batches.id'], name=op.f('fk_ingestion_corrections_batch_id_ingestion_batches'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ingestion_corrections'))
    )
    with op.batch_alter_table('ingestion_corrections', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ingestion_corrections_batch_id'), ['batch_id'], unique=False)

    op.create_table('projection_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fund_id', sa.Integer(), nullable=False),
    sa.Column('batch_id', sa.Integer(), nullable=False),
    sa.Column('version_no', sa.Integer(), nullable=False),
    sa.Column('cashflow_count', sa.Integer(), nullable=False),
    sa.Column('created_at', riskview.db.types.UtcDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['ingestion_batches.id'], name=op.f('fk_projection_versions_batch_id_ingestion_batches')),
    sa.ForeignKeyConstraint(['fund_id'], ['funds.id'], name=op.f('fk_projection_versions_fund_id_funds'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_projection_versions')),
    sa.UniqueConstraint('fund_id', 'version_no', name='uq_projection_versions_fund_version')
    )
    with op.batch_alter_table('projection_versions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_projection_versions_batch_id'), ['batch_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_projection_versions_fund_id'), ['fund_id'], unique=False)

    op.create_table('cashflows',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('version_id', sa.Integer(), nullable=False),
    sa.Column('source_row_id', sa.Integer(), nullable=False),
    sa.Column('cashflow_date', sa.Date(), nullable=False),
    sa.Column('cashflow_type', sa.String(length=32), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('amount_local', riskview.db.types.ExactDecimal(), nullable=False),
    sa.Column('amount_base', riskview.db.types.ExactDecimal(), nullable=False),
    sa.Column('base_currency', sa.String(length=3), nullable=False),
    sa.ForeignKeyConstraint(['base_currency'], ['currencies.code'], name=op.f('fk_cashflows_base_currency_currencies')),
    sa.ForeignKeyConstraint(['cashflow_type'], ['cashflow_types.code'], name=op.f('fk_cashflows_cashflow_type_cashflow_types')),
    sa.ForeignKeyConstraint(['currency'], ['currencies.code'], name=op.f('fk_cashflows_currency_currencies')),
    sa.ForeignKeyConstraint(['version_id'], ['projection_versions.id'], name=op.f('fk_cashflows_version_id_projection_versions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_cashflows')),
    sa.UniqueConstraint('version_id', 'currency', 'cashflow_date', 'cashflow_type', name='uq_cashflows_natural_key'),
    sa.UniqueConstraint('version_id', 'source_row_id', name='uq_cashflows_source_row')
    )
    with op.batch_alter_table('cashflows', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cashflows_version_id'), ['version_id'], unique=False)

    op.create_table('fund_current_version',
    sa.Column('fund_id', sa.Integer(), nullable=False),
    sa.Column('version_id', sa.Integer(), nullable=False),
    sa.Column('updated_at', riskview.db.types.UtcDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['fund_id'], ['funds.id'], name=op.f('fk_fund_current_version_fund_id_funds'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['version_id'], ['projection_versions.id'], name=op.f('fk_fund_current_version_version_id_projection_versions')),
    sa.PrimaryKeyConstraint('fund_id', name=op.f('pk_fund_current_version')),
    sa.UniqueConstraint('version_id', name=op.f('uq_fund_current_version_version_id'))
    )
    op.create_table('fx_forward_trades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('version_id', sa.Integer(), nullable=False),
    sa.Column('trade_date', sa.Date(), nullable=False),
    sa.Column('value_date', sa.Date(), nullable=False),
    sa.Column('sell_currency', sa.String(length=3), nullable=False),
    sa.Column('buy_currency', sa.String(length=3), nullable=False),
    sa.Column('notional_sell', riskview.db.types.ExactDecimal(), nullable=False),
    sa.Column('coverage_ratio', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['buy_currency'], ['currencies.code'], name=op.f('fk_fx_forward_trades_buy_currency_currencies')),
    sa.ForeignKeyConstraint(['sell_currency'], ['currencies.code'], name=op.f('fk_fx_forward_trades_sell_currency_currencies')),
    sa.ForeignKeyConstraint(['version_id'], ['projection_versions.id'], name=op.f('fk_fx_forward_trades_version_id_projection_versions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_fx_forward_trades'))
    )
    with op.batch_alter_table('fx_forward_trades', schema=None) as batch_op:
        batch_op.create_index('ix_fx_forward_trades_version_ccy_date', ['version_id', 'sell_currency', 'trade_date'], unique=False)

    op.create_table('nav_schedules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('version_id', sa.Integer(), nullable=False),
    sa.Column('scope', sa.String(length=8), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('irr', sa.Float(), nullable=False),
    sa.CheckConstraint("scope IN ('fund', 'position')", name=op.f('ck_nav_schedules_scope')),
    sa.ForeignKeyConstraint(['currency'], ['currencies.code'], name=op.f('fk_nav_schedules_currency_currencies')),
    sa.ForeignKeyConstraint(['version_id'], ['projection_versions.id'], name=op.f('fk_nav_schedules_version_id_projection_versions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_nav_schedules')),
    sa.UniqueConstraint('version_id', 'scope', 'currency', name='uq_nav_schedules_version_scope_ccy')
    )
    with op.batch_alter_table('nav_schedules', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_nav_schedules_version_id'), ['version_id'], unique=False)

    op.create_table('nav_points',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('schedule_id', sa.Integer(), nullable=False),
    sa.Column('point_date', sa.Date(), nullable=False),
    sa.Column('nav', riskview.db.types.ExactDecimal(), nullable=False),
    sa.Column('open_exposure', riskview.db.types.ExactDecimal(), nullable=False),
    sa.ForeignKeyConstraint(['schedule_id'], ['nav_schedules.id'], name=op.f('fk_nav_points_schedule_id_nav_schedules'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_nav_points')),
    sa.UniqueConstraint('schedule_id', 'point_date', name='uq_nav_points_schedule_date')
    )
    with op.batch_alter_table('nav_points', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_nav_points_schedule_id'), ['schedule_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('nav_points', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_nav_points_schedule_id'))

    op.drop_table('nav_points')
    with op.batch_alter_table('nav_schedules', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_nav_schedules_version_id'))

    op.drop_table('nav_schedules')
    with op.batch_alter_table('fx_forward_trades', schema=None) as batch_op:
        batch_op.drop_index('ix_fx_forward_trades_version_ccy_date')

    op.drop_table('fx_forward_trades')
    op.drop_table('fund_current_version')
    with op.batch_alter_table('cashflows', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cashflows_version_id'))

    op.drop_table('cashflows')
    with op.batch_alter_table('projection_versions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_projection_versions_fund_id'))
        batch_op.drop_index(batch_op.f('ix_projection_versions_batch_id'))

    op.drop_table('projection_versions')
    with op.batch_alter_table('ingestion_corrections', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ingestion_corrections_batch_id'))

    op.drop_table('ingestion_corrections')
    op.drop_table('funds')
    op.drop_table('ingestion_batches')
    op.drop_table('currencies')
    op.drop_table('cashflow_types')
    # ### end Alembic commands ###
