"""The migrations are the only source of schema truth, so they get tested.

Nothing in the application calls create_all, which means a model change without a
matching revision would otherwise surface as an OperationalError at deploy time.
"""

from alembic import command
from alembic.autogenerate import compare_metadata
from alembic.runtime.migration import MigrationContext
from sqlalchemy import text

from riskview.db import models  # noqa: F401  # registers the tables on Base.metadata
from riskview.db.alembic_support import alembic_config, current_and_head, schema_is_current
from riskview.db.base import Base
from riskview.db.session import create_db_engine
from riskview.schemas import CashflowType, CurrencyCode


def test_models_and_migrations_agree(engine):
    with engine.connect() as connection:
        context = MigrationContext.configure(
            connection, opts={"target_metadata": Base.metadata, "compare_type": True}
        )
        diff = compare_metadata(context, Base.metadata)

    assert diff == [], (
        "models have drifted from the migrations; run "
        "`uv run alembic revision --autogenerate -m '...'` and review the result"
    )


def test_schema_is_current_passes_on_a_migrated_database(engine):
    schema_is_current(engine)
    current, heads = current_and_head(engine)
    assert current == heads


def test_schema_is_current_fails_on_an_empty_database(tmp_path):
    engine = create_db_engine(f"sqlite+pysqlite:///{tmp_path / 'empty.db'}")
    try:
        exception = None
        try:
            schema_is_current(engine)
        except RuntimeError as caught:
            exception = caught
        assert exception is not None
        assert "alembic upgrade head" in str(exception)
    finally:
        engine.dispose()


def test_downgrade_and_upgrade_round_trip(tmp_path):
    """Proves the downgrades are real rather than autogenerated stubs."""
    url = f"sqlite+pysqlite:///{tmp_path / 'roundtrip.db'}"
    config = alembic_config(url)

    command.upgrade(config, "head")
    command.downgrade(config, "base")
    command.upgrade(config, "head")

    engine = create_db_engine(url)
    try:
        schema_is_current(engine)
    finally:
        engine.dispose()


def test_reference_data_matches_the_code_enums(session):
    """The closed sets in schemas.py and the reference tables must agree —
    a currency in one and not the other is a foreign-key violation at ingest."""
    currencies = set(session.execute(text("SELECT code FROM currencies")).scalars())
    types = set(session.execute(text("SELECT code FROM cashflow_types")).scalars())

    assert currencies == {member.value for member in CurrencyCode}
    assert types == {member.value for member in CashflowType}
