"""Generate the Case Study Report's dataset from the real pipeline.

The report page is static, but its numbers are not typed by hand: this script runs
`samples/cashflows.csv` through ingestion and analytics and writes the result as a
TypeScript module the frontend imports. Re-run it after any change to the analytics
or the sample data:

    uv run python scripts/build_report_data.py
"""

from __future__ import annotations

import json
import subprocess
from pathlib import Path

from riskview.analytics import compute_fund_analytics
from riskview.ingestion import ingest_file

ROOT = Path(__file__).resolve().parent.parent
SAMPLE = ROOT / "samples" / "cashflows.csv"
OUT = ROOT / "frontend" / "src" / "features" / "report" / "data.ts"


def _points(schedule) -> list[dict]:
    return [
        {"date": p.date.isoformat(), "nav": str(p.nav), "open": str(p.open_exposure)} for p in schedule.points
    ]


def _schedule(schedule) -> dict:
    return {"currency": schedule.currency, "irr": schedule.irr, "points": _points(schedule)}


def build() -> dict:
    result = ingest_file(SAMPLE)
    raw_lines = SAMPLE.read_text().splitlines()

    payload: dict = {
        "sourceFile": SAMPLE.name,
        "rawHeader": raw_lines[0],
        "rawRows": raw_lines[1:],
        "summary": result.summary(),
        "corrections": [
            {"line": c.line, "rowId": c.row_id, "corrections": list(c.corrections)}
            for c in result.corrections
        ],
        "funds": [],
    }

    names = sorted({cf.fund_name for cf in result.cashflows})
    for fund_id, name in enumerate(names, start=1):
        flows = [cf for cf in result.cashflows if cf.fund_name == name]
        a = compute_fund_analytics(fund_id, flows)
        payload["funds"].append(
            {
                "fundId": fund_id,
                "name": name,
                "baseCurrency": a.base_currency,
                "fundIrr": a.fund_irr,
                "currencyIrr": a.currency_irr,
                "cashflows": [
                    {
                        "id": cf.id,
                        "date": cf.cashflow_date.isoformat(),
                        "type": cf.cashflow_type.value,
                        "currency": cf.currency.value,
                        "local": str(cf.amount_local),
                        "base": str(cf.amount_base),
                    }
                    for cf in flows
                ],
                "navByCurrency": {c: _schedule(s) for c, s in a.nav_schedules.items()},
                "fundNav": _schedule(a.fund_nav_schedule),
                "hedges": [
                    {
                        "tradeDate": h.trade_date.isoformat(),
                        "valueDate": h.value_date.isoformat(),
                        "sell": h.sell_currency.value,
                        "buy": h.buy_currency.value,
                        "notional": str(h.notional_sell),
                        "coverage": h.coverage_ratio,
                    }
                    for h in a.hedges
                ],
            }
        )
    return payload


def test_counts() -> dict:
    """Test-suite size, asked of pytest rather than counted by hand.

    Parametrised cases make a `def test_` count wrong, and the report should quote the
    number that actually runs.
    """
    modules = len(sorted((ROOT / "tests").glob("test_*.py")))
    collected = subprocess.run(
        ["uv", "run", "pytest", "--collect-only", "-q"],
        capture_output=True,
        text=True,
        check=False,
        cwd=ROOT,
    )
    for line in collected.stdout.splitlines():
        if "tests collected" in line or "test collected" in line:
            return {"modules": modules, "tests": int(line.split()[0])}
    raise RuntimeError(f"could not read a test count from pytest:\n{collected.stdout}")


def main() -> None:
    payload = build()
    payload["tests"] = test_counts()
    payload["generatedFrom"] = "scripts/build_report_data.py"
    body = json.dumps(payload, indent=2, sort_keys=False)
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(
        "// Generated by scripts/build_report_data.py — do not hand-edit.\n"
        "// Every number here came out of src/riskview/, not out of a keyboard.\n"
        "// Regenerate after any change to the analytics or samples/cashflows.csv.\n\n"
        f"export const REPORT_DATA = {body} as const;\n\n"
        "export type ReportData = typeof REPORT_DATA;\n"
    )
    print(f"wrote {OUT.relative_to(ROOT)} ({OUT.stat().st_size / 1024:.0f} KB)")


if __name__ == "__main__":
    main()
