// Generated by scripts/build_report_data.py — do not hand-edit.
// Every number here came out of src/riskview/, not out of a keyboard.
// Regenerate after any change to the analytics or samples/cashflows.csv.

export const REPORT_DATA = {
  "sourceFile": "cashflows.csv",
  "rawHeader": "ID,Fund Name,Date,Cashflow Type,Local Currency,Cashflow Amount Local,Cashflow Amount Base,Base Currency",
  "rawRows": [
    "1,Fund I,30/09/2025 00:00,Investment,GBP,-100000000,-114573786,EUR",
    "2,Fund I,31/12/2025 00:00,Interest,GBP,2500000,2864345,EUR",
    "3,Fund I,31/03/2026 00:00,Interest,GBP,2500000,2864345,EUR",
    "4,Fund I,30/06/2026 00:00,Interest,GBP,2500000,2864345,EUR",
    "5,Fund I,30/09/2026 00:00,Interest,GBP,2500000,2864345,EUR",
    "6,Fund I,31/12/2026 00:00,Interest,GBP,2500000,2864345,EUR",
    "7,Fund I,31/03/2027 00:00,Interest,GBP,2500000,2864345,EUR",
    "8,Fund I,30/06/2027 00:00,Interest,GBP,2500000,2864345,EUR",
    "9,Fund I,30/09/2027 00:00,Interest,GBP,2500000,2864345,EUR",
    "10,Fund I,31/12/2027 00:00,Interest,GBP,2500000,2864345,EUR",
    "11,Fund I,31/03/2028 00:00,Interest,GBP,2500000,2864345,EUR",
    "12,Fund I,30/06/2028 00:00,Interest,GBP,2500000,2864345,EUR",
    "13,Fund I,30/09/2028 00:00,Interest,GBP,2500000,2864345,EUR",
    "14,Fund I,31/12/2028 00:00,Interest,GBP,2500000,2864345,EUR",
    "15,Fund I,31/03/2029 00:00,Interest,GBP,2500000,2864345,EUR",
    "16,Fund I,30/06/2029 00:00,Interest,GBP,2500000,2864345,EUR",
    "17,Fund I,30/09/2029 00:00,Interest,GPB,2500000,2864345,EUR",
    "18,Fund I,31/12/2029 00:00,Interest,GBP,2500000,2864345,EUR",
    "19,Fund I,31/03/2030 00:00,Interest,GBP,2500000,2864345,EUR",
    "20,Fund I,30/06/2030 00:00,Interest,GBP,2500000,2864345,EUR",
    "21,Fund I, 30/09/2030  00:00:00,Principal Repayment,GBP,100000000,114573786,EUR",
    "22,Fund I,30/09/2025 00:00,Investment,EUR,-150000000,-150000000,EUR",
    "23,Fund I,31/12/2025 00:00,Interest,EUR,3000000,3000000,EUR",
    "24,Fund I,31/03/2026 00:00,Interest,EUR,3000000,3000000,EUR",
    "25,Fund I,30/06/2026 00:00,Interest,EUR,3000000,3000000,EUR",
    "26,Fund I,30/09/2026 00:00,Interest,EUR,3000000,3000000,EUR",
    "27,Fund I,31/12/2026 00:00,Interest,EUR,3000000,3000000,EUR",
    "28,Fund I,31/03/2027 00:00,Interest,EUR,3000000,3000000,EUR",
    "29,Fund I,30/06/2027 00:00,Interest,EUR,3000000,3000000,EUR",
    "30,Fund I,30/09/2027 00:00,Interest,EUR,3000000,3000000,EUR",
    "31,Fund I,31/12/2027 00:00,Interest,EUR,3000000,3000000,EUR",
    "32,Fund I,31/03/2028 00:00,Interest,EUR,3000000,3000000,EUR",
    "33,Fund I,30/06/2028 00:00,Interest,EUR,3000000,3000000,EUR",
    "34,Fund I,30/09/2028 00:00,Interest,EUR,3000000,3000000,EUR",
    "35,Fund I,31/12/2028 00:00,Interest,EUR,3000000,3000000,EUR",
    "36,Fund I,31/03/2029 00:00,Interest,EUR,3000000,3000000,EUR",
    "37,Fund I,30/06/2029 00:00,Interest,EUR,3000000,3000000,EUR",
    "38,Fund I,30/09/2029 00:00,Interest,EUR,3000000,3000000,EUR",
    "39,Fund I,31/12/2029 00:00,Interest,EUR,3000000,3000000,EUR",
    "40,Fund I,31/03/2030 00:00,Interest,EUR,3000000,3000000,EUR",
    "41,Fund I,30/06/2030 00:00,Interest,EUR,3000000,3000000,EUR",
    "42,Fund I,30/09/2030 00:00,Principal Repayment,EUR,150000000,150000000,EUR",
    "43,Fund I,30/09/2025 00:00,Investment,USD,-200000000,-170212766,EUR",
    "44,Fund I,31/12/2025 00:00,Interest,USD,6000000,5106383,EUR",
    "45,Fund I,31/03/2026 00:00,Interest,USD,6000000,5106383,EUR",
    "46,Fund I,30/06/2026 00:00,Interest,USD,6000000,5106383,EUR",
    "47,Fund I,30/09/2026 00:00,Interest,USD,6000000,5106383,EUR",
    "48,Fund I,31/12/2026 00:00,Interest,USD,6000000,5106383,EUR",
    "49,Fund I,31/03/2027 00:00,Interest,USD,6000000,5106383,EUR",
    "50,Fund I,30/06/2027 00:00,Interest,USD,6000000,5106383,EUR",
    "51,Fund I,30/09/2027  00:00:00`,Interest,USD,6000000,5106383,EUR",
    "52,Fund I,31/12/2027 00:00,Interest,USD,6000000,5106383,EUR",
    "53,Fund I,31/03/2028 00:00,Interest,USD,6000000,5106383,EUR",
    "54,Fund I,30/06/2028 00:00,Interest,USD,6000000,5106383,EUR",
    "55,Fund I,30/09/2028 00:00,Interest,USD,6000000,5106383,EUR",
    "56,Fund I,31/12/2028 00:00,Interest,USD,6000000,5106383,EUR",
    "57,Fund I,31/03/2029 00:00,Interest,USD,6000000,5106383,EUR",
    "58,Fund I,30/06/2029 00:00,Interest,USD,6000000,5106383,EUR",
    "59,Fund I,30/09/2029 00:00,Interest,USD,6000000,5106383,EUR",
    "60,Fund I,31/12/2029 00:00,Interest,USD,6000000,5106383,EUR",
    "61,Fund I,31/03/2030 00:00,Interest,USD,6000000,5106383,EUR",
    "62,Fund I,30/06/2030 00:00,Interest,USD,6000000,5106383,EUR",
    "63,Fund I,30/09/2030 00:00,Principal Repayment,USD,200000000,170212766,EUR",
    "64,Fund II,30/09/2025 00:00,Investment,GBP,-140000000,-160403300,EUR",
    "65,Fund II,31/12/2025 00:00,Interest,GBP,3500000,4010082,EUR",
    "66,Fund II,31/03/2026 00:00,Interest,GBP,3500000,4010082,EUR",
    "67,Fund II,30/06/2026 00:00,Interest,GBP,3500000,4010082,EUR",
    "68,Fund II,30/09/2026 00:00,Interest,GBP,3500000,4010082,EUR",
    "69,Fund II,31/12/2026 00:00,Interest,GBP,3500000,4010082,EUR",
    "70,Fund II,31/03/2027 00:00,Interest,GBP,3500000,4010082,EUR",
    "71,Fund II,30/06/2027 00:00,Interest,GBP,3500000,4010082,EUR",
    "72,Fund II,30/09/2027 00:00,Interest,GBP,3500000,4010082,EUR",
    "73,Fund II,31/12/2027 00:00,Interest,GBP,3500000,4010082,EUR",
    "74,Fund II,31/03/2028 00:00,Interest,GBP,3500000,4010082,EUR",
    "75,Fund II,30/06/2028 00:00,Interest,GBP,3500000,4010082,EUR",
    "76,Fund II,30/09/2028 00:00,Interest,GBP,3500000,4010082,EUR",
    "77,Fund II,31/12/2028 00:00,Interest,GBP,3500000,4010082,EUR",
    "78,Fund II,31/03/2029 00:00,Interest,GBP,3500000,4010082,EUR",
    "79,Fund II,30/06/2029 00:00,Interest,GBP,3500000,4010082,EUR",
    "80,Fund II,30/09/2029 00:00,Interest,GBP,3500000,4010082,EUR",
    "81,Fund II,31/12/2029 00:00,Interest,GBP,3500000,4010082,EUR",
    "82,Fund II,31/03/2030 00:00,Interest,GBP,3500000,4010082,EUR",
    "83,Fund II,30/06/2030 00:00,Interest,GBP,3500000,4010082,EUR",
    "84,Fund II,30/09/2030 00:00,Principal Repayment,GBP,140000000,160403300,EUR",
    "85,Fund II,30/09/2025 00:00,Investment,EUR,-210000000,-210000000,EUR",
    "86,Fund II,31/12/2025 00:00,Interest,EUR,4200000,4200000,EUR",
    "87,Fund II,31/03/2026 00:00,Interest,EUR,4200000,4200000,EUR",
    "88,Fund II,30/06/2026 00:00,Interest,EUR,4200000,4200000,EUR",
    "89,Fund II,30/09/2026 00:00,Interest,EUR,4200000,4200000,EUR",
    "90,Fund II,31/12/2026 00:00,Interest,EUR,4200000,4200000,EUR",
    "91,Fund II,31/03/2027 00:00,Interest,EUR,4200000,4200000,EUR",
    "92,Fund II,30/06/2027 00:00,Interest,EUR,4200000,4200000,EUR",
    "93,Fund II,30/09/2027 00:00,Interest,EUR,4200000,4200000,EUR",
    "94,Fund II,31/12/2027 00:00,Interest,EUR,4200000,4200000,EUR",
    "95,Fund II,31/03/2028 00:00,Interest,EUR,4200000,4200000,EUR",
    "96,Fund II,30/06/2028 00:00,Interest,EUR,4200000,4200000,EUR",
    "97,Fund II,30/09/2028 00:00,Interest,EUR,4200000,4200000,EUR",
    "98,Fund II,31/12/2028 00:00,Interest,EUR,4200000,4200000,EUR",
    "99,Fund II,31/03/2029 00:00,Interest,EUR,4200000,4200000,EUR",
    "100,Fund II,30/06/2029 00:00,Interest,EUR,4200000,4200000,EUR",
    "101,Fund II,30/09/2029 00:00,Interest,EUR,4200000,4200000,EUR",
    "102,Fund II,31/12/2029 00:00,Interest,EUR,4200000,4200000,EUR",
    "103,Fund II,31/03/2030 00:00,Interest,EUR,4200000,4200000,EUR",
    "104,Fund II,30/06/2030 00:00,Interest,EUR,4200000,4200000,EUR",
    "105,Fund II,30/09/2030 00:00,Principal Repayment,EUR,210000000,210000000,EUR",
    "106,Fund II,30/09/2025 00:00,Investment,USD,-280000000,-238297872,EUR",
    "107,Fund II,31/12/2025 00:00,Interest,USD,8400000,7148936,EUR",
    "108,Fund II,31/03/2026 00:00,Interest,USD,8400000,7148936,EUR",
    "109,Fund II,30/06/2026 00:00,Interest,USD,8400000,7148936,EUR",
    "110,Fund II,30/09/2026 00:00,Interest,USD,8400000,7148936,EUR",
    "111,Fund II,31/12/2026 00:00,Interest,USD,8400000,7148936,EUR",
    "112,Fund II,31/03/2027 00:00,Interest,USD,8400000,7148936,EUR",
    "113,Fund II,30/06/2027 00:00,Interest,USD,8400000,7148936,EUR",
    "114,Fund II,30/09/2027 00:00,Interest,USD,8400000,7148936,EUR",
    "115,Fund II,31/12/2027 00:00,Interest,USD,8400000,7148936,EUR",
    "116,Fund II,31/03/2028 00:00,Interest,USD,8400000,7148936,EUR",
    "117,Fund II,30/06/2028 00:00,Interest,USD,8400000,7148936,EUR",
    "118,Fund II,30/09/2028 00:00,Interest,USD,8400000,7148936,EUR",
    "119,Fund II,31/12/2028 00:00,Interest,USD,8400000,7148936,EUR",
    "120,Fund II,31/03/2029 00:00,Interest,USD,8400000,7148936,EUR",
    "121,Fund II,30/06/2029 00:00,Interest,USD,8400000,7148936,EUR",
    "122,Fund II,30/09/2029 00:00,Interest,USD,8400000,7148936,EUR",
    "123,Fund II,31/12/2029 00:00,Interest,USD,8400000,7148936,EUR",
    "124,Fund II,31/03/2030 00:00,Interest,USD,8400000,7148936,EUR",
    "125,Fund II,30/06/2030 00:00,Interest,USD,8400000,7148936,EUR",
    "126,Fund II,30/09/2030 00:00,Principal Repayment,USD,280000000,238297872,EUR"
  ],
  "summary": {
    "accepted": 126,
    "corrected": 3
  },
  "corrections": [
    {
      "line": 18,
      "rowId": "17",
      "corrections": [
        "currency: corrected typo 'GPB' -> 'GBP'"
      ]
    },
    {
      "line": 22,
      "rowId": "21",
      "corrections": [
        "cashflow_date: scrubbed ' 30/09/2030  00:00:00' -> '30/09/2030 00:00:00'"
      ]
    },
    {
      "line": 52,
      "rowId": "51",
      "corrections": [
        "cashflow_date: scrubbed '30/09/2027  00:00:00`' -> '30/09/2027 00:00:00'"
      ]
    }
  ],
  "funds": [
    {
      "fundId": 1,
      "name": "Fund I",
      "baseCurrency": "EUR",
      "fundIrr": 0.1004756317370454,
      "currencyIrr": {
        "GBP": 0.09950722477610066,
        "EUR": 0.07887049043981995,
        "USD": 0.12051546680600328
      },
      "cashflows": [
        {
          "id": 1,
          "date": "2025-09-30",
          "type": "Investment",
          "currency": "GBP",
          "local": "-100000000",
          "base": "-114573786"
        },
        {
          "id": 2,
          "date": "2025-12-31",
          "type": "Interest",
          "currency": "GBP",
          "local": "2500000",
          "base": "2864345"
        },
        {
          "id": 3,
          "date": "2026-03-31",
          "type": "Interest",
          "currency": "GBP",
          "local": "2500000",
          "base": "2864345"
        },
        {
          "id": 4,
          "date": "2026-06-30",
          "type": "Interest",
          "currency": "GBP",
          "local": "2500000",
          "base": "2864345"
        },
        {
          "id": 5,
          "date": "2026-09-30",
          "type": "Interest",
          "currency": "GBP",
          "local": "2500000",
          "base": "2864345"
        },
        {
          "id": 6,
          "date": "2026-12-31",
          "type": "Interest",
          "currency": "GBP",
          "local": "2500000",
          "base": "2864345"
        },
        {
          "id": 7,
          "date": "2027-03-31",
          "type": "Interest",
          "currency": "GBP",
          "local": "2500000",
          "base": "2864345"
        },
        {
          "id": 8,
          "date": "2027-06-30",
          "type": "Interest",
          "currency": "GBP",
          "local": "2500000",
          "base": "2864345"
        },
        {
          "id": 9,
          "date": "2027-09-30",
          "type": "Interest",
          "currency": "GBP",
          "local": "2500000",
          "base": "2864345"
        },
        {
          "id": 10,
          "date": "2027-12-31",
          "type": "Interest",
          "currency": "GBP",
          "local": "2500000",
          "base": "2864345"
        },
        {
          "id": 11,
          "date": "2028-03-31",
          "type": "Interest",
          "currency": "GBP",
          "local": "2500000",
          "base": "2864345"
        },
        {
          "id": 12,
          "date": "2028-06-30",
          "type": "Interest",
          "currency": "GBP",
          "local": "2500000",
          "base": "2864345"
        },
        {
          "id": 13,
          "date": "2028-09-30",
          "type": "Interest",
          "currency": "GBP",
          "local": "2500000",
          "base": "2864345"
        },
        {
          "id": 14,
          "date": "2028-12-31",
          "type": "Interest",
          "currency": "GBP",
          "local": "2500000",
          "base": "2864345"
        },
        {
          "id": 15,
          "date": "2029-03-31",
          "type": "Interest",
          "currency": "GBP",
          "local": "2500000",
          "base": "2864345"
        },
        {
          "id": 16,
          "date": "2029-06-30",
          "type": "Interest",
          "currency": "GBP",
          "local": "2500000",
          "base": "2864345"
        },
        {
          "id": 17,
          "date": "2029-09-30",
          "type": "Interest",
          "currency": "GBP",
          "local": "2500000",
          "base": "2864345"
        },
        {
          "id": 18,
          "date": "2029-12-31",
          "type": "Interest",
          "currency": "GBP",
          "local": "2500000",
          "base": "2864345"
        },
        {
          "id": 19,
          "date": "2030-03-31",
          "type": "Interest",
          "currency": "GBP",
          "local": "2500000",
          "base": "2864345"
        },
        {
          "id": 20,
          "date": "2030-06-30",
          "type": "Interest",
          "currency": "GBP",
          "local": "2500000",
          "base": "2864345"
        },
        {
          "id": 21,
          "date": "2030-09-30",
          "type": "Principal Repayment",
          "currency": "GBP",
          "local": "100000000",
          "base": "114573786"
        },
        {
          "id": 22,
          "date": "2025-09-30",
          "type": "Investment",
          "currency": "EUR",
          "local": "-150000000",
          "base": "-150000000"
        },
        {
          "id": 23,
          "date": "2025-12-31",
          "type": "Interest",
          "currency": "EUR",
          "local": "3000000",
          "base": "3000000"
        },
        {
          "id": 24,
          "date": "2026-03-31",
          "type": "Interest",
          "currency": "EUR",
          "local": "3000000",
          "base": "3000000"
        },
        {
          "id": 25,
          "date": "2026-06-30",
          "type": "Interest",
          "currency": "EUR",
          "local": "3000000",
          "base": "3000000"
        },
        {
          "id": 26,
          "date": "2026-09-30",
          "type": "Interest",
          "currency": "EUR",
          "local": "3000000",
          "base": "3000000"
        },
        {
          "id": 27,
          "date": "2026-12-31",
          "type": "Interest",
          "currency": "EUR",
          "local": "3000000",
          "base": "3000000"
        },
        {
          "id": 28,
          "date": "2027-03-31",
          "type": "Interest",
          "currency": "EUR",
          "local": "3000000",
          "base": "3000000"
        },
        {
          "id": 29,
          "date": "2027-06-30",
          "type": "Interest",
          "currency": "EUR",
          "local": "3000000",
          "base": "3000000"
        },
        {
          "id": 30,
          "date": "2027-09-30",
          "type": "Interest",
          "currency": "EUR",
          "local": "3000000",
          "base": "3000000"
        },
        {
          "id": 31,
          "date": "2027-12-31",
          "type": "Interest",
          "currency": "EUR",
          "local": "3000000",
          "base": "3000000"
        },
        {
          "id": 32,
          "date": "2028-03-31",
          "type": "Interest",
          "currency": "EUR",
          "local": "3000000",
          "base": "3000000"
        },
        {
          "id": 33,
          "date": "2028-06-30",
          "type": "Interest",
          "currency": "EUR",
          "local": "3000000",
          "base": "3000000"
        },
        {
          "id": 34,
          "date": "2028-09-30",
          "type": "Interest",
          "currency": "EUR",
          "local": "3000000",
          "base": "3000000"
        },
        {
          "id": 35,
          "date": "2028-12-31",
          "type": "Interest",
          "currency": "EUR",
          "local": "3000000",
          "base": "3000000"
        },
        {
          "id": 36,
          "date": "2029-03-31",
          "type": "Interest",
          "currency": "EUR",
          "local": "3000000",
          "base": "3000000"
        },
        {
          "id": 37,
          "date": "2029-06-30",
          "type": "Interest",
          "currency": "EUR",
          "local": "3000000",
          "base": "3000000"
        },
        {
          "id": 38,
          "date": "2029-09-30",
          "type": "Interest",
          "currency": "EUR",
          "local": "3000000",
          "base": "3000000"
        },
        {
          "id": 39,
          "date": "2029-12-31",
          "type": "Interest",
          "currency": "EUR",
          "local": "3000000",
          "base": "3000000"
        },
        {
          "id": 40,
          "date": "2030-03-31",
          "type": "Interest",
          "currency": "EUR",
          "local": "3000000",
          "base": "3000000"
        },
        {
          "id": 41,
          "date": "2030-06-30",
          "type": "Interest",
          "currency": "EUR",
          "local": "3000000",
          "base": "3000000"
        },
        {
          "id": 42,
          "date": "2030-09-30",
          "type": "Principal Repayment",
          "currency": "EUR",
          "local": "150000000",
          "base": "150000000"
        },
        {
          "id": 43,
          "date": "2025-09-30",
          "type": "Investment",
          "currency": "USD",
          "local": "-200000000",
          "base": "-170212766"
        },
        {
          "id": 44,
          "date": "2025-12-31",
          "type": "Interest",
          "currency": "USD",
          "local": "6000000",
          "base": "5106383"
        },
        {
          "id": 45,
          "date": "2026-03-31",
          "type": "Interest",
          "currency": "USD",
          "local": "6000000",
          "base": "5106383"
        },
        {
          "id": 46,
          "date": "2026-06-30",
          "type": "Interest",
          "currency": "USD",
          "local": "6000000",
          "base": "5106383"
        },
        {
          "id": 47,
          "date": "2026-09-30",
          "type": "Interest",
          "currency": "USD",
          "local": "6000000",
          "base": "5106383"
        },
        {
          "id": 48,
          "date": "2026-12-31",
          "type": "Interest",
          "currency": "USD",
          "local": "6000000",
          "base": "5106383"
        },
        {
          "id": 49,
          "date": "2027-03-31",
          "type": "Interest",
          "currency": "USD",
          "local": "6000000",
          "base": "5106383"
        },
        {
          "id": 50,
          "date": "2027-06-30",
          "type": "Interest",
          "currency": "USD",
          "local": "6000000",
          "base": "5106383"
        },
        {
          "id": 51,
          "date": "2027-09-30",
          "type": "Interest",
          "currency": "USD",
          "local": "6000000",
          "base": "5106383"
        },
        {
          "id": 52,
          "date": "2027-12-31",
          "type": "Interest",
          "currency": "USD",
          "local": "6000000",
          "base": "5106383"
        },
        {
          "id": 53,
          "date": "2028-03-31",
          "type": "Interest",
          "currency": "USD",
          "local": "6000000",
          "base": "5106383"
        },
        {
          "id": 54,
          "date": "2028-06-30",
          "type": "Interest",
          "currency": "USD",
          "local": "6000000",
          "base": "5106383"
        },
        {
          "id": 55,
          "date": "2028-09-30",
          "type": "Interest",
          "currency": "USD",
          "local": "6000000",
          "base": "5106383"
        },
        {
          "id": 56,
          "date": "2028-12-31",
          "type": "Interest",
          "currency": "USD",
          "local": "6000000",
          "base": "5106383"
        },
        {
          "id": 57,
          "date": "2029-03-31",
          "type": "Interest",
          "currency": "USD",
          "local": "6000000",
          "base": "5106383"
        },
        {
          "id": 58,
          "date": "2029-06-30",
          "type": "Interest",
          "currency": "USD",
          "local": "6000000",
          "base": "5106383"
        },
        {
          "id": 59,
          "date": "2029-09-30",
          "type": "Interest",
          "currency": "USD",
          "local": "6000000",
          "base": "5106383"
        },
        {
          "id": 60,
          "date": "2029-12-31",
          "type": "Interest",
          "currency": "USD",
          "local": "6000000",
          "base": "5106383"
        },
        {
          "id": 61,
          "date": "2030-03-31",
          "type": "Interest",
          "currency": "USD",
          "local": "6000000",
          "base": "5106383"
        },
        {
          "id": 62,
          "date": "2030-06-30",
          "type": "Interest",
          "currency": "USD",
          "local": "6000000",
          "base": "5106383"
        },
        {
          "id": 63,
          "date": "2030-09-30",
          "type": "Principal Repayment",
          "currency": "USD",
          "local": "200000000",
          "base": "170212766"
        }
      ],
      "navByCurrency": {
        "GBP": {
          "currency": "GBP",
          "irr": 0.09950722477610066,
          "points": [
            {
              "date": "2025-09-30",
              "nav": "0.00",
              "open": "100000000.00"
            },
            {
              "date": "2025-12-31",
              "nav": "102419859.44",
              "open": "99919859.44"
            },
            {
              "date": "2026-03-31",
              "nav": "102284599.01",
              "open": "99784599.01"
            },
            {
              "date": "2026-06-30",
              "nav": "102172688.30",
              "open": "99672688.30"
            },
            {
              "date": "2026-09-30",
              "nav": "102084627.26",
              "open": "99584627.26"
            },
            {
              "date": "2026-12-31",
              "nav": "101994435.26",
              "open": "99494435.26"
            },
            {
              "date": "2027-03-31",
              "nav": "101849106.59",
              "open": "99349106.59"
            },
            {
              "date": "2027-06-30",
              "nav": "101726773.49",
              "open": "99226773.49"
            },
            {
              "date": "2027-09-30",
              "nav": "101627921.93",
              "open": "99127921.93"
            },
            {
              "date": "2027-12-31",
              "nav": "101526678.30",
              "open": "99026678.30"
            },
            {
              "date": "2028-03-31",
              "nav": "101396628.70",
              "open": "98896628.70"
            },
            {
              "date": "2028-06-30",
              "nav": "101263466.69",
              "open": "98763466.69"
            },
            {
              "date": "2028-09-30",
              "nav": "101153403.76",
              "open": "98653403.76"
            },
            {
              "date": "2028-12-31",
              "nav": "101040677.46",
              "open": "98540677.46"
            },
            {
              "date": "2029-03-31",
              "nav": "100872776.81",
              "open": "98372776.81"
            },
            {
              "date": "2029-06-30",
              "nav": "100727077.75",
              "open": "98227077.75"
            },
            {
              "date": "2029-09-30",
              "nav": "100604034.96",
              "open": "98104034.96"
            },
            {
              "date": "2029-12-31",
              "nav": "100478014.71",
              "open": "97978014.71"
            },
            {
              "date": "2030-03-31",
              "nav": "100296797.88",
              "open": "97796797.88"
            },
            {
              "date": "2030-06-30",
              "nav": "100137314.24",
              "open": "97637314.24"
            },
            {
              "date": "2030-09-30",
              "nav": "100000000.00",
              "open": "0.00"
            }
          ]
        },
        "EUR": {
          "currency": "EUR",
          "irr": 0.07887049043981995,
          "points": [
            {
              "date": "2025-09-30",
              "nav": "0.00",
              "open": "150000000.00"
            },
            {
              "date": "2025-12-31",
              "nav": "152897833.90",
              "open": "149897833.90"
            },
            {
              "date": "2026-03-31",
              "nav": "152730149.57",
              "open": "149730149.57"
            },
            {
              "date": "2026-06-30",
              "nav": "152591030.26",
              "open": "149591030.26"
            },
            {
              "date": "2026-09-30",
              "nav": "152480963.31",
              "open": "149480963.31"
            },
            {
              "date": "2026-12-31",
              "nav": "152368769.99",
              "open": "149368769.99"
            },
            {
              "date": "2027-03-31",
              "nav": "152191089.02",
              "open": "149191089.02"
            },
            {
              "date": "2027-06-30",
              "nav": "152041669.92",
              "open": "149041669.92"
            },
            {
              "date": "2027-09-30",
              "nav": "151920989.94",
              "open": "148920989.94"
            },
            {
              "date": "2027-12-31",
              "nav": "151797978.56",
              "open": "148797978.56"
            },
            {
              "date": "2028-03-31",
              "nav": "151641048.33",
              "open": "148641048.33"
            },
            {
              "date": "2028-06-30",
              "nav": "151481119.65",
              "open": "148481119.65"
            },
            {
              "date": "2028-09-30",
              "nav": "151349610.46",
              "open": "148349610.46"
            },
            {
              "date": "2028-12-31",
              "nav": "151215560.66",
              "open": "148215560.66"
            },
            {
              "date": "2029-03-31",
              "nav": "151016089.83",
              "open": "148016089.83"
            },
            {
              "date": "2029-06-30",
              "nav": "150844220.12",
              "open": "147844220.12"
            },
            {
              "date": "2029-09-30",
              "nav": "150700406.74",
              "open": "147700406.74"
            },
            {
              "date": "2029-12-31",
              "nav": "150553815.04",
              "open": "147553815.04"
            },
            {
              "date": "2030-03-31",
              "nav": "150341840.54",
              "open": "147341840.54"
            },
            {
              "date": "2030-06-30",
              "nav": "150157088.02",
              "open": "147157088.02"
            },
            {
              "date": "2030-09-30",
              "nav": "150000000.00",
              "open": "0.00"
            }
          ]
        },
        "USD": {
          "currency": "USD",
          "irr": 0.12051546680600328,
          "points": [
            {
              "date": "2025-09-30",
              "nav": "0.00",
              "open": "200000000.00"
            },
            {
              "date": "2025-12-31",
              "nav": "205819255.59",
              "open": "199819255.59"
            },
            {
              "date": "2026-03-31",
              "nav": "205505079.74",
              "open": "199505079.74"
            },
            {
              "date": "2026-06-30",
              "nav": "205245939.56",
              "open": "199245939.56"
            },
            {
              "date": "2026-09-30",
              "nav": "205043254.80",
              "open": "199043254.80"
            },
            {
              "date": "2026-12-31",
              "nav": "204834672.66",
              "open": "198834672.66"
            },
            {
              "date": "2027-03-31",
              "nav": "204492480.67",
              "open": "198492480.67"
            },
            {
              "date": "2027-06-30",
              "nav": "204204202.44",
              "open": "198204202.44"
            },
            {
              "date": "2027-09-30",
              "nav": "203971207.00",
              "open": "197971207.00"
            },
            {
              "date": "2027-12-31",
              "nav": "203731432.27",
              "open": "197731432.27"
            },
            {
              "date": "2028-03-31",
              "nav": "203421254.48",
              "open": "197421254.48"
            },
            {
              "date": "2028-06-30",
              "nav": "203102151.17",
              "open": "197102151.17"
            },
            {
              "date": "2028-09-30",
              "nav": "202837090.14",
              "open": "196837090.14"
            },
            {
              "date": "2028-12-31",
              "nav": "202564316.83",
              "open": "196564316.83"
            },
            {
              "date": "2029-03-31",
              "nav": "202157522.23",
              "open": "196157522.23"
            },
            {
              "date": "2029-06-30",
              "nav": "201802054.39",
              "open": "195802054.39"
            },
            {
              "date": "2029-09-30",
              "nav": "201499165.39",
              "open": "195499165.39"
            },
            {
              "date": "2029-12-31",
              "nav": "201187463.44",
              "open": "195187463.44"
            },
            {
              "date": "2030-03-31",
              "nav": "200741490.71",
              "open": "194741490.71"
            },
            {
              "date": "2030-06-30",
              "nav": "200345275.84",
              "open": "194345275.84"
            },
            {
              "date": "2030-09-30",
              "nav": "200000000.00",
              "open": "0.00"
            }
          ]
        }
      },
      "fundNav": {
        "currency": "EUR",
        "irr": 0.1004756317370454,
        "points": [
          {
            "date": "2025-09-30",
            "nav": "0.00",
            "open": "434786552.00"
          },
          {
            "date": "2025-12-31",
            "nav": "445406601.59",
            "open": "434435873.59"
          },
          {
            "date": "2026-03-31",
            "nav": "444813939.68",
            "open": "433843211.68"
          },
          {
            "date": "2026-06-30",
            "nav": "444323654.34",
            "open": "433352926.34"
          },
          {
            "date": "2026-09-30",
            "nav": "443937958.35",
            "open": "432967230.35"
          },
          {
            "date": "2026-12-31",
            "nav": "443542841.39",
            "open": "432572113.39"
          },
          {
            "date": "2027-03-31",
            "nav": "442905656.85",
            "open": "431934928.85"
          },
          {
            "date": "2027-06-30",
            "nav": "442369272.71",
            "open": "431398544.71"
          },
          {
            "date": "2027-09-30",
            "nav": "441935839.21",
            "open": "430965111.21"
          },
          {
            "date": "2027-12-31",
            "nav": "441491818.70",
            "open": "430521090.70"
          },
          {
            "date": "2028-03-31",
            "nav": "440921280.17",
            "open": "429950552.17"
          },
          {
            "date": "2028-06-30",
            "nav": "440336959.03",
            "open": "429366231.03"
          },
          {
            "date": "2028-09-30",
            "nav": "439853884.45",
            "open": "428883156.45"
          },
          {
            "date": "2028-12-31",
            "nav": "439359010.34",
            "open": "428388282.34"
          },
          {
            "date": "2029-03-31",
            "nav": "438621879.92",
            "open": "427651151.92"
          },
          {
            "date": "2029-06-30",
            "nav": "437982011.67",
            "open": "427011283.67"
          },
          {
            "date": "2029-09-30",
            "nav": "437441415.40",
            "open": "426470687.40"
          },
          {
            "date": "2029-12-31",
            "nav": "436887614.58",
            "open": "425916886.58"
          },
          {
            "date": "2030-03-31",
            "nav": "436091445.97",
            "open": "425120717.97"
          },
          {
            "date": "2030-06-30",
            "nav": "435390449.49",
            "open": "424419721.49"
          },
          {
            "date": "2030-09-30",
            "nav": "434786552.00",
            "open": "0.00"
          }
        ]
      },
      "hedges": [
        {
          "tradeDate": "2025-09-30",
          "valueDate": "2025-12-31",
          "sell": "GBP",
          "buy": "EUR",
          "notional": "100000000.00",
          "coverage": 1.0
        },
        {
          "tradeDate": "2025-12-31",
          "valueDate": "2026-03-31",
          "sell": "GBP",
          "buy": "EUR",
          "notional": "99919859.44",
          "coverage": 1.0
        },
        {
          "tradeDate": "2026-03-31",
          "valueDate": "2026-06-30",
          "sell": "GBP",
          "buy": "EUR",
          "notional": "99784599.01",
          "coverage": 1.0
        },
        {
          "tradeDate": "2026-06-30",
          "valueDate": "2026-09-30",
          "sell": "GBP",
          "buy": "EUR",
          "notional": "99672688.30",
          "coverage": 1.0
        },
        {
          "tradeDate": "2026-09-30",
          "valueDate": "2026-12-31",
          "sell": "GBP",
          "buy": "EUR",
          "notional": "99584627.26",
          "coverage": 1.0
        },
        {
          "tradeDate": "2026-12-31",
          "valueDate": "2027-03-31",
          "sell": "GBP",
          "buy": "EUR",
          "notional": "99494435.26",
          "coverage": 1.0
        },
        {
          "tradeDate": "2027-03-31",
          "valueDate": "2027-06-30",
          "sell": "GBP",
          "buy": "EUR",
          "notional": "99349106.59",
          "coverage": 1.0
        },
        {
          "tradeDate": "2027-06-30",
          "valueDate": "2027-09-30",
          "sell": "GBP",
          "buy": "EUR",
          "notional": "99226773.49",
          "coverage": 1.0
        },
        {
          "tradeDate": "2027-09-30",
          "valueDate": "2027-12-31",
          "sell": "GBP",
          "buy": "EUR",
          "notional": "99127921.93",
          "coverage": 1.0
        },
        {
          "tradeDate": "2027-12-31",
          "valueDate": "2028-03-31",
          "sell": "GBP",
          "buy": "EUR",
          "notional": "99026678.30",
          "coverage": 1.0
        },
        {
          "tradeDate": "2028-03-31",
          "valueDate": "2028-06-30",
          "sell": "GBP",
          "buy": "EUR",
          "notional": "98896628.70",
          "coverage": 1.0
        },
        {
          "tradeDate": "2028-06-30",
          "valueDate": "2028-09-30",
          "sell": "GBP",
          "buy": "EUR",
          "notional": "98763466.69",
          "coverage": 1.0
        },
        {
          "tradeDate": "2028-09-30",
          "valueDate": "2028-12-31",
          "sell": "GBP",
          "buy": "EUR",
          "notional": "98653403.76",
          "coverage": 1.0
        },
        {
          "tradeDate": "2028-12-31",
          "valueDate": "2029-03-31",
          "sell": "GBP",
          "buy": "EUR",
          "notional": "98540677.46",
          "coverage": 1.0
        },
        {
          "tradeDate": "2029-03-31",
          "valueDate": "2029-06-30",
          "sell": "GBP",
          "buy": "EUR",
          "notional": "98372776.81",
          "coverage": 1.0
        },
        {
          "tradeDate": "2029-06-30",
          "valueDate": "2029-09-30",
          "sell": "GBP",
          "buy": "EUR",
          "notional": "98227077.75",
          "coverage": 1.0
        },
        {
          "tradeDate": "2029-09-30",
          "valueDate": "2029-12-31",
          "sell": "GBP",
          "buy": "EUR",
          "notional": "98104034.96",
          "coverage": 1.0
        },
        {
          "tradeDate": "2029-12-31",
          "valueDate": "2030-03-31",
          "sell": "GBP",
          "buy": "EUR",
          "notional": "97978014.71",
          "coverage": 1.0
        },
        {
          "tradeDate": "2030-03-31",
          "valueDate": "2030-06-30",
          "sell": "GBP",
          "buy": "EUR",
          "notional": "97796797.88",
          "coverage": 1.0
        },
        {
          "tradeDate": "2030-06-30",
          "valueDate": "2030-09-30",
          "sell": "GBP",
          "buy": "EUR",
          "notional": "97637314.24",
          "coverage": 1.0
        },
        {
          "tradeDate": "2025-09-30",
          "valueDate": "2025-12-31",
          "sell": "USD",
          "buy": "EUR",
          "notional": "200000000.00",
          "coverage": 1.0
        },
        {
          "tradeDate": "2025-12-31",
          "valueDate": "2026-03-31",
          "sell": "USD",
          "buy": "EUR",
          "notional": "199819255.59",
          "coverage": 1.0
        },
        {
          "tradeDate": "2026-03-31",
          "valueDate": "2026-06-30",
          "sell": "USD",
          "buy": "EUR",
          "notional": "199505079.74",
          "coverage": 1.0
        },
        {
          "tradeDate": "2026-06-30",
          "valueDate": "2026-09-30",
          "sell": "USD",
          "buy": "EUR",
          "notional": "199245939.56",
          "coverage": 1.0
        },
        {
          "tradeDate": "2026-09-30",
          "valueDate": "2026-12-31",
          "sell": "USD",
          "buy": "EUR",
          "notional": "199043254.80",
          "coverage": 1.0
        },
        {
          "tradeDate": "2026-12-31",
          "valueDate": "2027-03-31",
          "sell": "USD",
          "buy": "EUR",
          "notional": "198834672.66",
          "coverage": 1.0
        },
        {
          "tradeDate": "2027-03-31",
          "valueDate": "2027-06-30",
          "sell": "USD",
          "buy": "EUR",
          "notional": "198492480.67",
          "coverage": 1.0
        },
        {
          "tradeDate": "2027-06-30",
          "valueDate": "2027-09-30",
          "sell": "USD",
          "buy": "EUR",
          "notional": "198204202.44",
          "coverage": 1.0
        },
        {
          "tradeDate": "2027-09-30",
          "valueDate": "2027-12-31",
          "sell": "USD",
          "buy": "EUR",
          "notional": "197971207.00",
          "coverage": 1.0
        },
        {
          "tradeDate": "2027-12-31",
          "valueDate": "2028-03-31",
          "sell": "USD",
          "buy": "EUR",
          "notional": "197731432.27",
          "coverage": 1.0
        },
        {
          "tradeDate": "2028-03-31",
          "valueDate": "2028-06-30",
          "sell": "USD",
          "buy": "EUR",
          "notional": "197421254.48",
          "coverage": 1.0
        },
        {
          "tradeDate": "2028-06-30",
          "valueDate": "2028-09-30",
          "sell": "USD",
          "buy": "EUR",
          "notional": "197102151.17",
          "coverage": 1.0
        },
        {
          "tradeDate": "2028-09-30",
          "valueDate": "2028-12-31",
          "sell": "USD",
          "buy": "EUR",
          "notional": "196837090.14",
          "coverage": 1.0
        },
        {
          "tradeDate": "2028-12-31",
          "valueDate": "2029-03-31",
          "sell": "USD",
          "buy": "EUR",
          "notional": "196564316.83",
          "coverage": 1.0
        },
        {
          "tradeDate": "2029-03-31",
          "valueDate": "2029-06-30",
          "sell": "USD",
          "buy": "EUR",
          "notional": "196157522.23",
          "coverage": 1.0
        },
        {
          "tradeDate": "2029-06-30",
          "valueDate": "2029-09-30",
          "sell": "USD",
          "buy": "EUR",
          "notional": "195802054.39",
          "coverage": 1.0
        },
        {
          "tradeDate": "2029-09-30",
          "valueDate": "2029-12-31",
          "sell": "USD",
          "buy": "EUR",
          "notional": "195499165.39",
          "coverage": 1.0
        },
        {
          "tradeDate": "2029-12-31",
          "valueDate": "2030-03-31",
          "sell": "USD",
          "buy": "EUR",
          "notional": "195187463.44",
          "coverage": 1.0
        },
        {
          "tradeDate": "2030-03-31",
          "valueDate": "2030-06-30",
          "sell": "USD",
          "buy": "EUR",
          "notional": "194741490.71",
          "coverage": 1.0
        },
        {
          "tradeDate": "2030-06-30",
          "valueDate": "2030-09-30",
          "sell": "USD",
          "buy": "EUR",
          "notional": "194345275.84",
          "coverage": 1.0
        }
      ]
    },
    {
      "fundId": 2,
      "name": "Fund II",
      "baseCurrency": "EUR",
      "fundIrr": 0.1004756236578424,
      "currencyIrr": {
        "GBP": 0.09950722477610066,
        "EUR": 0.07887049043981995,
        "USD": 0.12051546680600328
      },
      "cashflows": [
        {
          "id": 64,
          "date": "2025-09-30",
          "type": "Investment",
          "currency": "GBP",
          "local": "-140000000",
          "base": "-160403300"
        },
        {
          "id": 65,
          "date": "2025-12-31",
          "type": "Interest",
          "currency": "GBP",
          "local": "3500000",
          "base": "4010082"
        },
        {
          "id": 66,
          "date": "2026-03-31",
          "type": "Interest",
          "currency": "GBP",
          "local": "3500000",
          "base": "4010082"
        },
        {
          "id": 67,
          "date": "2026-06-30",
          "type": "Interest",
          "currency": "GBP",
          "local": "3500000",
          "base": "4010082"
        },
        {
          "id": 68,
          "date": "2026-09-30",
          "type": "Interest",
          "currency": "GBP",
          "local": "3500000",
          "base": "4010082"
        },
        {
          "id": 69,
          "date": "2026-12-31",
          "type": "Interest",
          "currency": "GBP",
          "local": "3500000",
          "base": "4010082"
        },
        {
          "id": 70,
          "date": "2027-03-31",
          "type": "Interest",
          "currency": "GBP",
          "local": "3500000",
          "base": "4010082"
        },
        {
          "id": 71,
          "date": "2027-06-30",
          "type": "Interest",
          "currency": "GBP",
          "local": "3500000",
          "base": "4010082"
        },
        {
          "id": 72,
          "date": "2027-09-30",
          "type": "Interest",
          "currency": "GBP",
          "local": "3500000",
          "base": "4010082"
        },
        {
          "id": 73,
          "date": "2027-12-31",
          "type": "Interest",
          "currency": "GBP",
          "local": "3500000",
          "base": "4010082"
        },
        {
          "id": 74,
          "date": "2028-03-31",
          "type": "Interest",
          "currency": "GBP",
          "local": "3500000",
          "base": "4010082"
        },
        {
          "id": 75,
          "date": "2028-06-30",
          "type": "Interest",
          "currency": "GBP",
          "local": "3500000",
          "base": "4010082"
        },
        {
          "id": 76,
          "date": "2028-09-30",
          "type": "Interest",
          "currency": "GBP",
          "local": "3500000",
          "base": "4010082"
        },
        {
          "id": 77,
          "date": "2028-12-31",
          "type": "Interest",
          "currency": "GBP",
          "local": "3500000",
          "base": "4010082"
        },
        {
          "id": 78,
          "date": "2029-03-31",
          "type": "Interest",
          "currency": "GBP",
          "local": "3500000",
          "base": "4010082"
        },
        {
          "id": 79,
          "date": "2029-06-30",
          "type": "Interest",
          "currency": "GBP",
          "local": "3500000",
          "base": "4010082"
        },
        {
          "id": 80,
          "date": "2029-09-30",
          "type": "Interest",
          "currency": "GBP",
          "local": "3500000",
          "base": "4010082"
        },
        {
          "id": 81,
          "date": "2029-12-31",
          "type": "Interest",
          "currency": "GBP",
          "local": "3500000",
          "base": "4010082"
        },
        {
          "id": 82,
          "date": "2030-03-31",
          "type": "Interest",
          "currency": "GBP",
          "local": "3500000",
          "base": "4010082"
        },
        {
          "id": 83,
          "date": "2030-06-30",
          "type": "Interest",
          "currency": "GBP",
          "local": "3500000",
          "base": "4010082"
        },
        {
          "id": 84,
          "date": "2030-09-30",
          "type": "Principal Repayment",
          "currency": "GBP",
          "local": "140000000",
          "base": "160403300"
        },
        {
          "id": 85,
          "date": "2025-09-30",
          "type": "Investment",
          "currency": "EUR",
          "local": "-210000000",
          "base": "-210000000"
        },
        {
          "id": 86,
          "date": "2025-12-31",
          "type": "Interest",
          "currency": "EUR",
          "local": "4200000",
          "base": "4200000"
        },
        {
          "id": 87,
          "date": "2026-03-31",
          "type": "Interest",
          "currency": "EUR",
          "local": "4200000",
          "base": "4200000"
        },
        {
          "id": 88,
          "date": "2026-06-30",
          "type": "Interest",
          "currency": "EUR",
          "local": "4200000",
          "base": "4200000"
        },
        {
          "id": 89,
          "date": "2026-09-30",
          "type": "Interest",
          "currency": "EUR",
          "local": "4200000",
          "base": "4200000"
        },
        {
          "id": 90,
          "date": "2026-12-31",
          "type": "Interest",
          "currency": "EUR",
          "local": "4200000",
          "base": "4200000"
        },
        {
          "id": 91,
          "date": "2027-03-31",
          "type": "Interest",
          "currency": "EUR",
          "local": "4200000",
          "base": "4200000"
        },
        {
          "id": 92,
          "date": "2027-06-30",
          "type": "Interest",
          "currency": "EUR",
          "local": "4200000",
          "base": "4200000"
        },
        {
          "id": 93,
          "date": "2027-09-30",
          "type": "Interest",
          "currency": "EUR",
          "local": "4200000",
          "base": "4200000"
        },
        {
          "id": 94,
          "date": "2027-12-31",
          "type": "Interest",
          "currency": "EUR",
          "local": "4200000",
          "base": "4200000"
        },
        {
          "id": 95,
          "date": "2028-03-31",
          "type": "Interest",
          "currency": "EUR",
          "local": "4200000",
          "base": "4200000"
        },
        {
          "id": 96,
          "date": "2028-06-30",
          "type": "Interest",
          "currency": "EUR",
          "local": "4200000",
          "base": "4200000"
        },
        {
          "id": 97,
          "date": "2028-09-30",
          "type": "Interest",
          "currency": "EUR",
          "local": "4200000",
          "base": "4200000"
        },
        {
          "id": 98,
          "date": "2028-12-31",
          "type": "Interest",
          "currency": "EUR",
          "local": "4200000",
          "base": "4200000"
        },
        {
          "id": 99,
          "date": "2029-03-31",
          "type": "Interest",
          "currency": "EUR",
          "local": "4200000",
          "base": "4200000"
        },
        {
          "id": 100,
          "date": "2029-06-30",
          "type": "Interest",
          "currency": "EUR",
          "local": "4200000",
          "base": "4200000"
        },
        {
          "id": 101,
          "date": "2029-09-30",
          "type": "Interest",
          "currency": "EUR",
          "local": "4200000",
          "base": "4200000"
        },
        {
          "id": 102,
          "date": "2029-12-31",
          "type": "Interest",
          "currency": "EUR",
          "local": "4200000",
          "base": "4200000"
        },
        {
          "id": 103,
          "date": "2030-03-31",
          "type": "Interest",
          "currency": "EUR",
          "local": "4200000",
          "base": "4200000"
        },
        {
          "id": 104,
          "date": "2030-06-30",
          "type": "Interest",
          "currency": "EUR",
          "local": "4200000",
          "base": "4200000"
        },
        {
          "id": 105,
          "date": "2030-09-30",
          "type": "Principal Repayment",
          "currency": "EUR",
          "local": "210000000",
          "base": "210000000"
        },
        {
          "id": 106,
          "date": "2025-09-30",
          "type": "Investment",
          "currency": "USD",
          "local": "-280000000",
          "base": "-238297872"
        },
        {
          "id": 107,
          "date": "2025-12-31",
          "type": "Interest",
          "currency": "USD",
          "local": "8400000",
          "base": "7148936"
        },
        {
          "id": 108,
          "date": "2026-03-31",
          "type": "Interest",
          "currency": "USD",
          "local": "8400000",
          "base": "7148936"
        },
        {
          "id": 109,
          "date": "2026-06-30",
          "type": "Interest",
          "currency": "USD",
          "local": "8400000",
          "base": "7148936"
        },
        {
          "id": 110,
          "date": "2026-09-30",
          "type": "Interest",
          "currency": "USD",
          "local": "8400000",
          "base": "7148936"
        },
        {
          "id": 111,
          "date": "2026-12-31",
          "type": "Interest",
          "currency": "USD",
          "local": "8400000",
          "base": "7148936"
        },
        {
          "id": 112,
          "date": "2027-03-31",
          "type": "Interest",
          "currency": "USD",
          "local": "8400000",
          "base": "7148936"
        },
        {
          "id": 113,
          "date": "2027-06-30",
          "type": "Interest",
          "currency": "USD",
          "local": "8400000",
          "base": "7148936"
        },
        {
          "id": 114,
          "date": "2027-09-30",
          "type": "Interest",
          "currency": "USD",
          "local": "8400000",
          "base": "7148936"
        },
        {
          "id": 115,
          "date": "2027-12-31",
          "type": "Interest",
          "currency": "USD",
          "local": "8400000",
          "base": "7148936"
        },
        {
          "id": 116,
          "date": "2028-03-31",
          "type": "Interest",
          "currency": "USD",
          "local": "8400000",
          "base": "7148936"
        },
        {
          "id": 117,
          "date": "2028-06-30",
          "type": "Interest",
          "currency": "USD",
          "local": "8400000",
          "base": "7148936"
        },
        {
          "id": 118,
          "date": "2028-09-30",
          "type": "Interest",
          "currency": "USD",
          "local": "8400000",
          "base": "7148936"
        },
        {
          "id": 119,
          "date": "2028-12-31",
          "type": "Interest",
          "currency": "USD",
          "local": "8400000",
          "base": "7148936"
        },
        {
          "id": 120,
          "date": "2029-03-31",
          "type": "Interest",
          "currency": "USD",
          "local": "8400000",
          "base": "7148936"
        },
        {
          "id": 121,
          "date": "2029-06-30",
          "type": "Interest",
          "currency": "USD",
          "local": "8400000",
          "base": "7148936"
        },
        {
          "id": 122,
          "date": "2029-09-30",
          "type": "Interest",
          "currency": "USD",
          "local": "8400000",
          "base": "7148936"
        },
        {
          "id": 123,
          "date": "2029-12-31",
          "type": "Interest",
          "currency": "USD",
          "local": "8400000",
          "base": "7148936"
        },
        {
          "id": 124,
          "date": "2030-03-31",
          "type": "Interest",
          "currency": "USD",
          "local": "8400000",
          "base": "7148936"
        },
        {
          "id": 125,
          "date": "2030-06-30",
          "type": "Interest",
          "currency": "USD",
          "local": "8400000",
          "base": "7148936"
        },
        {
          "id": 126,
          "date": "2030-09-30",
          "type": "Principal Repayment",
          "currency": "USD",
          "local": "280000000",
          "base": "238297872"
        }
      ],
      "navByCurrency": {
        "GBP": {
          "currency": "GBP",
          "irr": 0.09950722477610066,
          "points": [
            {
              "date": "2025-09-30",
              "nav": "0.00",
              "open": "140000000.00"
            },
            {
              "date": "2025-12-31",
              "nav": "143387803.21",
              "open": "139887803.21"
            },
            {
              "date": "2026-03-31",
              "nav": "143198438.62",
              "open": "139698438.62"
            },
            {
              "date": "2026-06-30",
              "nav": "143041763.63",
              "open": "139541763.63"
            },
            {
              "date": "2026-09-30",
              "nav": "142918478.16",
              "open": "139418478.16"
            },
            {
              "date": "2026-12-31",
              "nav": "142792209.36",
              "open": "139292209.36"
            },
            {
              "date": "2027-03-31",
              "nav": "142588749.23",
              "open": "139088749.23"
            },
            {
              "date": "2027-06-30",
              "nav": "142417482.88",
              "open": "138917482.88"
            },
            {
              "date": "2027-09-30",
              "nav": "142279090.70",
              "open": "138779090.70"
            },
            {
              "date": "2027-12-31",
              "nav": "142137349.62",
              "open": "138637349.62"
            },
            {
              "date": "2028-03-31",
              "nav": "141955280.18",
              "open": "138455280.18"
            },
            {
              "date": "2028-06-30",
              "nav": "141768853.37",
              "open": "138268853.37"
            },
            {
              "date": "2028-09-30",
              "nav": "141614765.26",
              "open": "138114765.26"
            },
            {
              "date": "2028-12-31",
              "nav": "141456948.44",
              "open": "137956948.44"
            },
            {
              "date": "2029-03-31",
              "nav": "141221887.54",
              "open": "137721887.54"
            },
            {
              "date": "2029-06-30",
              "nav": "141017908.85",
              "open": "137517908.85"
            },
            {
              "date": "2029-09-30",
              "nav": "140845648.95",
              "open": "137345648.95"
            },
            {
              "date": "2029-12-31",
              "nav": "140669220.59",
              "open": "137169220.59"
            },
            {
              "date": "2030-03-31",
              "nav": "140415517.04",
              "open": "136915517.04"
            },
            {
              "date": "2030-06-30",
              "nav": "140192239.93",
              "open": "136692239.93"
            },
            {
              "date": "2030-09-30",
              "nav": "140000000.00",
              "open": "0.00"
            }
          ]
        },
        "EUR": {
          "currency": "EUR",
          "irr": 0.07887049043981995,
          "points": [
            {
              "date": "2025-09-30",
              "nav": "0.00",
              "open": "210000000.00"
            },
            {
              "date": "2025-12-31",
              "nav": "214056967.45",
              "open": "209856967.45"
            },
            {
              "date": "2026-03-31",
              "nav": "213822209.40",
              "open": "209622209.40"
            },
            {
              "date": "2026-06-30",
              "nav": "213627442.36",
              "open": "209427442.36"
            },
            {
              "date": "2026-09-30",
              "nav": "213473348.63",
              "open": "209273348.63"
            },
            {
              "date": "2026-12-31",
              "nav": "213316277.99",
              "open": "209116277.99"
            },
            {
              "date": "2027-03-31",
              "nav": "213067524.63",
              "open": "208867524.63"
            },
            {
              "date": "2027-06-30",
              "nav": "212858337.89",
              "open": "208658337.89"
            },
            {
              "date": "2027-09-30",
              "nav": "212689385.92",
              "open": "208489385.92"
            },
            {
              "date": "2027-12-31",
              "nav": "212517169.98",
              "open": "208317169.98"
            },
            {
              "date": "2028-03-31",
              "nav": "212297467.66",
              "open": "208097467.66"
            },
            {
              "date": "2028-06-30",
              "nav": "212073567.52",
              "open": "207873567.52"
            },
            {
              "date": "2028-09-30",
              "nav": "211889454.65",
              "open": "207689454.65"
            },
            {
              "date": "2028-12-31",
              "nav": "211701784.92",
              "open": "207501784.92"
            },
            {
              "date": "2029-03-31",
              "nav": "211422525.76",
              "open": "207222525.76"
            },
            {
              "date": "2029-06-30",
              "nav": "211181908.17",
              "open": "206981908.17"
            },
            {
              "date": "2029-09-30",
              "nav": "210980569.44",
              "open": "206780569.44"
            },
            {
              "date": "2029-12-31",
              "nav": "210775341.05",
              "open": "206575341.05"
            },
            {
              "date": "2030-03-31",
              "nav": "210478576.76",
              "open": "206278576.76"
            },
            {
              "date": "2030-06-30",
              "nav": "210219923.22",
              "open": "206019923.22"
            },
            {
              "date": "2030-09-30",
              "nav": "210000000.00",
              "open": "0.00"
            }
          ]
        },
        "USD": {
          "currency": "USD",
          "irr": 0.12051546680600328,
          "points": [
            {
              "date": "2025-09-30",
              "nav": "0.00",
              "open": "280000000.00"
            },
            {
              "date": "2025-12-31",
              "nav": "288146957.83",
              "open": "279746957.83"
            },
            {
              "date": "2026-03-31",
              "nav": "287707111.64",
              "open": "279307111.64"
            },
            {
              "date": "2026-06-30",
              "nav": "287344315.39",
              "open": "278944315.39"
            },
            {
              "date": "2026-09-30",
              "nav": "287060556.72",
              "open": "278660556.72"
            },
            {
              "date": "2026-12-31",
              "nav": "286768541.73",
              "open": "278368541.73"
            },
            {
              "date": "2027-03-31",
              "nav": "286289472.94",
              "open": "277889472.94"
            },
            {
              "date": "2027-06-30",
              "nav": "285885883.41",
              "open": "277485883.41"
            },
            {
              "date": "2027-09-30",
              "nav": "285559689.80",
              "open": "277159689.80"
            },
            {
              "date": "2027-12-31",
              "nav": "285224005.17",
              "open": "276824005.17"
            },
            {
              "date": "2028-03-31",
              "nav": "284789756.27",
              "open": "276389756.27"
            },
            {
              "date": "2028-06-30",
              "nav": "284343011.64",
              "open": "275943011.64"
            },
            {
              "date": "2028-09-30",
              "nav": "283971926.20",
              "open": "275571926.20"
            },
            {
              "date": "2028-12-31",
              "nav": "283590043.56",
              "open": "275190043.56"
            },
            {
              "date": "2029-03-31",
              "nav": "283020531.13",
              "open": "274620531.13"
            },
            {
              "date": "2029-06-30",
              "nav": "282522876.14",
              "open": "274122876.14"
            },
            {
              "date": "2029-09-30",
              "nav": "282098831.54",
              "open": "273698831.54"
            },
            {
              "date": "2029-12-31",
              "nav": "281662448.82",
              "open": "273262448.82"
            },
            {
              "date": "2030-03-31",
              "nav": "281038086.99",
              "open": "272638086.99"
            },
            {
              "date": "2030-06-30",
              "nav": "280483386.17",
              "open": "272083386.17"
            },
            {
              "date": "2030-09-30",
              "nav": "280000000.00",
              "open": "0.00"
            }
          ]
        }
      },
      "fundNav": {
        "currency": "EUR",
        "irr": 0.1004756236578424,
        "points": [
          {
            "date": "2025-09-30",
            "nav": "0.00",
            "open": "608701172.00"
          },
          {
            "date": "2025-12-31",
            "nav": "623569240.26",
            "open": "608210222.26"
          },
          {
            "date": "2026-03-31",
            "nav": "622739513.64",
            "open": "607380495.64"
          },
          {
            "date": "2026-06-30",
            "nav": "622053114.20",
            "open": "606694096.20"
          },
          {
            "date": "2026-09-30",
            "nav": "621513139.85",
            "open": "606154121.85"
          },
          {
            "date": "2026-12-31",
            "nav": "620959976.14",
            "open": "605600958.14"
          },
          {
            "date": "2027-03-31",
            "nav": "620067917.85",
            "open": "604708899.85"
          },
          {
            "date": "2027-06-30",
            "nav": "619316980.11",
            "open": "603957962.11"
          },
          {
            "date": "2027-09-30",
            "nav": "618710173.24",
            "open": "603351155.24"
          },
          {
            "date": "2027-12-31",
            "nav": "618088544.58",
            "open": "602729526.58"
          },
          {
            "date": "2028-03-31",
            "nav": "617289790.71",
            "open": "601930772.71"
          },
          {
            "date": "2028-06-30",
            "nav": "616471741.17",
            "open": "601112723.17"
          },
          {
            "date": "2028-09-30",
            "nav": "615795436.80",
            "open": "600436418.80"
          },
          {
            "date": "2028-12-31",
            "nav": "615102613.11",
            "open": "599743595.11"
          },
          {
            "date": "2029-03-31",
            "nav": "614070630.60",
            "open": "598711612.60"
          },
          {
            "date": "2029-06-30",
            "nav": "613174815.14",
            "open": "597815797.14"
          },
          {
            "date": "2029-09-30",
            "nav": "612417980.42",
            "open": "597058962.42"
          },
          {
            "date": "2029-12-31",
            "nav": "611642659.34",
            "open": "596283641.34"
          },
          {
            "date": "2030-03-31",
            "nav": "610528023.38",
            "open": "595169005.38"
          },
          {
            "date": "2030-06-30",
            "nav": "609546628.41",
            "open": "594187610.41"
          },
          {
            "date": "2030-09-30",
            "nav": "608701172.00",
            "open": "0.00"
          }
        ]
      },
      "hedges": [
        {
          "tradeDate": "2025-09-30",
          "valueDate": "2025-12-31",
          "sell": "GBP",
          "buy": "EUR",
          "notional": "140000000.00",
          "coverage": 1.0
        },
        {
          "tradeDate": "2025-12-31",
          "valueDate": "2026-03-31",
          "sell": "GBP",
          "buy": "EUR",
          "notional": "139887803.21",
          "coverage": 1.0
        },
        {
          "tradeDate": "2026-03-31",
          "valueDate": "2026-06-30",
          "sell": "GBP",
          "buy": "EUR",
          "notional": "139698438.62",
          "coverage": 1.0
        },
        {
          "tradeDate": "2026-06-30",
          "valueDate": "2026-09-30",
          "sell": "GBP",
          "buy": "EUR",
          "notional": "139541763.63",
          "coverage": 1.0
        },
        {
          "tradeDate": "2026-09-30",
          "valueDate": "2026-12-31",
          "sell": "GBP",
          "buy": "EUR",
          "notional": "139418478.16",
          "coverage": 1.0
        },
        {
          "tradeDate": "2026-12-31",
          "valueDate": "2027-03-31",
          "sell": "GBP",
          "buy": "EUR",
          "notional": "139292209.36",
          "coverage": 1.0
        },
        {
          "tradeDate": "2027-03-31",
          "valueDate": "2027-06-30",
          "sell": "GBP",
          "buy": "EUR",
          "notional": "139088749.23",
          "coverage": 1.0
        },
        {
          "tradeDate": "2027-06-30",
          "valueDate": "2027-09-30",
          "sell": "GBP",
          "buy": "EUR",
          "notional": "138917482.88",
          "coverage": 1.0
        },
        {
          "tradeDate": "2027-09-30",
          "valueDate": "2027-12-31",
          "sell": "GBP",
          "buy": "EUR",
          "notional": "138779090.70",
          "coverage": 1.0
        },
        {
          "tradeDate": "2027-12-31",
          "valueDate": "2028-03-31",
          "sell": "GBP",
          "buy": "EUR",
          "notional": "138637349.62",
          "coverage": 1.0
        },
        {
          "tradeDate": "2028-03-31",
          "valueDate": "2028-06-30",
          "sell": "GBP",
          "buy": "EUR",
          "notional": "138455280.18",
          "coverage": 1.0
        },
        {
          "tradeDate": "2028-06-30",
          "valueDate": "2028-09-30",
          "sell": "GBP",
          "buy": "EUR",
          "notional": "138268853.37",
          "coverage": 1.0
        },
        {
          "tradeDate": "2028-09-30",
          "valueDate": "2028-12-31",
          "sell": "GBP",
          "buy": "EUR",
          "notional": "138114765.26",
          "coverage": 1.0
        },
        {
          "tradeDate": "2028-12-31",
          "valueDate": "2029-03-31",
          "sell": "GBP",
          "buy": "EUR",
          "notional": "137956948.44",
          "coverage": 1.0
        },
        {
          "tradeDate": "2029-03-31",
          "valueDate": "2029-06-30",
          "sell": "GBP",
          "buy": "EUR",
          "notional": "137721887.54",
          "coverage": 1.0
        },
        {
          "tradeDate": "2029-06-30",
          "valueDate": "2029-09-30",
          "sell": "GBP",
          "buy": "EUR",
          "notional": "137517908.85",
          "coverage": 1.0
        },
        {
          "tradeDate": "2029-09-30",
          "valueDate": "2029-12-31",
          "sell": "GBP",
          "buy": "EUR",
          "notional": "137345648.95",
          "coverage": 1.0
        },
        {
          "tradeDate": "2029-12-31",
          "valueDate": "2030-03-31",
          "sell": "GBP",
          "buy": "EUR",
          "notional": "137169220.59",
          "coverage": 1.0
        },
        {
          "tradeDate": "2030-03-31",
          "valueDate": "2030-06-30",
          "sell": "GBP",
          "buy": "EUR",
          "notional": "136915517.04",
          "coverage": 1.0
        },
        {
          "tradeDate": "2030-06-30",
          "valueDate": "2030-09-30",
          "sell": "GBP",
          "buy": "EUR",
          "notional": "136692239.93",
          "coverage": 1.0
        },
        {
          "tradeDate": "2025-09-30",
          "valueDate": "2025-12-31",
          "sell": "USD",
          "buy": "EUR",
          "notional": "280000000.00",
          "coverage": 1.0
        },
        {
          "tradeDate": "2025-12-31",
          "valueDate": "2026-03-31",
          "sell": "USD",
          "buy": "EUR",
          "notional": "279746957.83",
          "coverage": 1.0
        },
        {
          "tradeDate": "2026-03-31",
          "valueDate": "2026-06-30",
          "sell": "USD",
          "buy": "EUR",
          "notional": "279307111.64",
          "coverage": 1.0
        },
        {
          "tradeDate": "2026-06-30",
          "valueDate": "2026-09-30",
          "sell": "USD",
          "buy": "EUR",
          "notional": "278944315.39",
          "coverage": 1.0
        },
        {
          "tradeDate": "2026-09-30",
          "valueDate": "2026-12-31",
          "sell": "USD",
          "buy": "EUR",
          "notional": "278660556.72",
          "coverage": 1.0
        },
        {
          "tradeDate": "2026-12-31",
          "valueDate": "2027-03-31",
          "sell": "USD",
          "buy": "EUR",
          "notional": "278368541.73",
          "coverage": 1.0
        },
        {
          "tradeDate": "2027-03-31",
          "valueDate": "2027-06-30",
          "sell": "USD",
          "buy": "EUR",
          "notional": "277889472.94",
          "coverage": 1.0
        },
        {
          "tradeDate": "2027-06-30",
          "valueDate": "2027-09-30",
          "sell": "USD",
          "buy": "EUR",
          "notional": "277485883.41",
          "coverage": 1.0
        },
        {
          "tradeDate": "2027-09-30",
          "valueDate": "2027-12-31",
          "sell": "USD",
          "buy": "EUR",
          "notional": "277159689.80",
          "coverage": 1.0
        },
        {
          "tradeDate": "2027-12-31",
          "valueDate": "2028-03-31",
          "sell": "USD",
          "buy": "EUR",
          "notional": "276824005.17",
          "coverage": 1.0
        },
        {
          "tradeDate": "2028-03-31",
          "valueDate": "2028-06-30",
          "sell": "USD",
          "buy": "EUR",
          "notional": "276389756.27",
          "coverage": 1.0
        },
        {
          "tradeDate": "2028-06-30",
          "valueDate": "2028-09-30",
          "sell": "USD",
          "buy": "EUR",
          "notional": "275943011.64",
          "coverage": 1.0
        },
        {
          "tradeDate": "2028-09-30",
          "valueDate": "2028-12-31",
          "sell": "USD",
          "buy": "EUR",
          "notional": "275571926.20",
          "coverage": 1.0
        },
        {
          "tradeDate": "2028-12-31",
          "valueDate": "2029-03-31",
          "sell": "USD",
          "buy": "EUR",
          "notional": "275190043.56",
          "coverage": 1.0
        },
        {
          "tradeDate": "2029-03-31",
          "valueDate": "2029-06-30",
          "sell": "USD",
          "buy": "EUR",
          "notional": "274620531.13",
          "coverage": 1.0
        },
        {
          "tradeDate": "2029-06-30",
          "valueDate": "2029-09-30",
          "sell": "USD",
          "buy": "EUR",
          "notional": "274122876.14",
          "coverage": 1.0
        },
        {
          "tradeDate": "2029-09-30",
          "valueDate": "2029-12-31",
          "sell": "USD",
          "buy": "EUR",
          "notional": "273698831.54",
          "coverage": 1.0
        },
        {
          "tradeDate": "2029-12-31",
          "valueDate": "2030-03-31",
          "sell": "USD",
          "buy": "EUR",
          "notional": "273262448.82",
          "coverage": 1.0
        },
        {
          "tradeDate": "2030-03-31",
          "valueDate": "2030-06-30",
          "sell": "USD",
          "buy": "EUR",
          "notional": "272638086.99",
          "coverage": 1.0
        },
        {
          "tradeDate": "2030-06-30",
          "valueDate": "2030-09-30",
          "sell": "USD",
          "buy": "EUR",
          "notional": "272083386.17",
          "coverage": 1.0
        }
      ]
    }
  ],
  "tests": {
    "modules": 8,
    "tests": 94
  },
  "generatedFrom": "scripts/build_report_data.py"
} as const;

export type ReportData = typeof REPORT_DATA;
